TODO_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("tasks.urls", namespace="tasks")),

]

tasks/urls.py
from django.urls import path

from .views import (
    TaskListView,
    TagsListView,
    CreateTaskView,
    CreateTagView,
    UpdateTaskView,
    DeleteTaskView,
    UpdateTagView,
    DeleteTagView,
    mark_task_undone,
    mark_task_done,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("tags/", TagsListView.as_view(), name="tag-list"),
    path("task/create/", CreateTaskView.as_view(), name="task-create"),
    path("tag/create/", CreateTagView.as_view(), name="tag-create"),
    path("task/<int:pk>/update/", UpdateTaskView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", DeleteTaskView.as_view(), name="task-delete"),
    path("tag/<int:pk>/update/", UpdateTagView.as_view(), name="tag-update"),
    path("tag/<int:pk>/delete/", DeleteTagView.as_view(), name="tag-delete"),
    path('task/<int:pk>/mark_done/', mark_task_done, name='mark-task-done'),
    path('task/<int:pk>/mark_undone/', mark_task_undone, name='mark-task-undone'),

]

app_name = "tasks"

tasks/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    done = models.BooleanField(default=False)
    date = models.DateField(auto_now_add=True)
    tags = models.ManyToManyField(Tag, related_name='tasks')

    def __str__(self):
        return f"{self.title}, {self.done}, {self.date}, {self.tags}, {self.description}"

tasks/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from .models import Tag, Task


class TaskListView(generic.ListView):
    model = Task
    paginate_by = 5
    template_name = "tasks/index.html"


class CreateTaskView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("tasks:index")


class UpdateTaskView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("tasks:index")


class DeleteTaskView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:index")


class TagsListView(generic.ListView):
    model = Tag
    paginate_by = 5


class CreateTagView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")


class UpdateTagView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")


class DeleteTagView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tasks:tag-list")


def mark_task_done(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.done = True
    task.save()
    return redirect('tasks:index')


def mark_task_undone(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.done = False
    task.save()
    return redirect('tasks:index')

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>TODO list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'tasks:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'tasks:tag-list' %}">Tags</a></li>
</ul>

templates/tasks/index.html
{% extends "base.html" %}

{% block content %}
  <h1>
    TODO list
    <a style="float: right" href="{% url 'tasks:task-create' %}" class="btn btn-primary link-to-page">
      Add task
    </a>
  </h1>
  <br>
  {% if task_list %}
    <ul>
      {% for task in task_list %}
        <li class="task-box">
          <p>
            <strong>{{ task.title }}

              {% if task.done %}
                <span class="done">Done</span>
              {% else %}
                <span class="not-done">Not Done</span>
              {% endif %}
              {% if task.done %}
                <a style="float: right" href="{% url 'tasks:mark-task-undone' pk=task.pk %}" class="btn btn-secondary link-to-page">Undo</a>
              {% else %}
                <a style="float: right" href="{% url 'tasks:mark-task-done' pk=task.pk %}" class="btn btn-primary link-to-page btn-done">Complete</a>
              {% endif %}


            </strong>
          </p>
          <p>
            <strong>Created</strong>: {{ task.date }}
          </p>
          <p>
            Tags:
            {% for tag in task.tags.all %}
              {{ tag }}
            {% endfor %}
            <a href="{% url "tasks:task-update" pk=task.id %}">Update</a>
            <a href="{% url "tasks:task-delete" pk=task.id %}">Delete</a>
          </p>
        </li>
        <br>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no tasks yet</p>
  {% endif %}

{% endblock %}

templates/tasks/tag_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <h1>Delete task</h1>

  <p>Are you sure to delete tag: {{ tag }}</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url "tasks:tag-list" %}" class="btn btn-primary">No</a>
  </form>
{% endblock %}

templates/tasks/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags
    <a style="float: right" href="{% url 'tasks:tag-create' %}" class="btn btn-primary link-to-page">
      Add
    </a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
            {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'tasks:tag-update' pk=tag.pk %}" class="btn btn-secondary">Update</a>
          </td>
          <td>
            <a href="{% url 'tasks:tag-delete' pk=tag.pk %}" class="btn btn-secondary">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no tags in the service.</p>
  {% endif %}
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <h1>Delete task</h1>

  <p>Are you sure to delete task: {{ task.title }}</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url "tasks:index" %}" class="btn btn-primary">No</a>
  </form>
{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

{% endblock %}